version: "3"
services:
  web:
    build:
      context: .
      dockerfile: MyHouseMaid/Dockerfile
    ports: 
        - 8000:80
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "MYSuperPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"